# config.yaml
knowledge_base:
  base_dir: ./kbs # Relative path to the project root for KB storage

embedding_model:
  provider: openai # or another provider like 'huggingface', 'cohere'
  base_url: null # Optional: Specify if using a custom API endpoint
  model_name: text-embedding-3-small # Example OpenAI model
  api_key: ${OPENAI_API_KEY} # Use environment variable OPENAI_API_KEY

language_model:
  provider: openai # or another provider
  base_url: null # Optional
  model_name: gpt-4o # Example OpenAI model
  api_key: ${OPENAI_API_KEY} # Use the same or a different env var

logging:
  level: INFO # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null # Optional: Specify a file path like ./app.log
